// Compiled contract artifacts for Arc Testnet deployment
// Generated by scripts/compileContracts.js — solc 0.8.34, optimizer 200 runs

import bytecodes from "./bytecodes.json";

// ── ERC-20 Token ──────────────────────────────────────────────────────────────
// Re-exports the same verified ERC-20 used for mock USDC
export {
  MOCK_USDC_ABI as ERC20_TOKEN_ABI,
  MOCK_USDC_BYTECODE as ERC20_TOKEN_BYTECODE,
} from "./mockUsdcArtifact";

// ── ERC-721 NFT ───────────────────────────────────────────────────────────────
// MockERC721(string name_, string symbol_) — public mint, auto-increment tokenId
export const ERC721_NFT_ABI = [
  "constructor(string name_, string symbol_)",
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address owner) view returns (uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function mint(address to) returns (uint256)",
  "function approve(address to, uint256 tokenId)",
  "function getApproved(uint256 tokenId) view returns (address)",
  "function transferFrom(address from, address to, uint256 tokenId)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
];

export const ERC721_NFT_BYTECODE: string = bytecodes.erc721.bytecode;
