// Compiled ERC-20 artifact — generated by scripts/compileContracts.js
// Source: solc 0.8.34, optimizer 200 runs
// Contract: MockERC20(string name, string symbol) — decimals=6, public mint

import bytecodes from "./bytecodes.json";

export const MOCK_USDC_ABI = [
  "constructor(string name, string symbol)",
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "function mint(address to, uint256 amount)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
];

export const MOCK_USDC_BYTECODE: string = bytecodes.erc20.bytecode;
